# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Wings Blogs
subtitle:
keywords:
author: Wings
language: "zh-CN"
timezone: UTC

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://GTRgoSky.github.io.git
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Site settings 设置title 邮箱 头像等...
SEOTitle: Wings Blog
email: 314912145@qq.com
description: "在dev部署"
keyword: ""
header-img: https://user-images.githubusercontent.com/21190726/95844791-e770cd00-0d7b-11eb-8a30-e603ad5bac22.png
# https://user-images.githubusercontent.com/21190726/54736315-7855e580-4be5-11e9-8403-e5f1ac1a41a4.png
article-img: https://raw.githubusercontent.com/GTRgoSky/GTRgoSky.github.io/release/blog/img/user.jpg
header-img-article: https://user-images.githubusercontent.com/21190726/54735802-1e542080-4be3-11e9-9df9-9fb5875bd3e7.png
404-img: /img/header_img/404.png
signature: false #show signature
signature-img: img/signature/BeanTechSign-white.png 

# SNS settings //设置底部icon
# RSS: false
# weibo_username:     Demonbaneen
# zhihu_username:     Demonbane
github_username:    GTRgoSky
# twitter_username:   Demonbane_x
#facebook_username:  YenYuHsuan
#linkedin_username:  huweihuang

# Build settings
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

## Featured Tags //设置tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: huweihuang

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: https://github.com/GTRgoSky/GTRgoSky.github.io.git
  branch: master

# Sidebar settings 设置侧边头像
sidebar: true                       # whether or not using Sidebar.
sidebar-about-description: ""
sidebar-avatar: https://img-blog.csdnimg.cn/20200506141449764.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`
widgets:
- featured-tags
- short-about
- recent-posts
- friends-blog
- archive
#- category

# widget behavior
## Archive
archives-img: /img/header_img/archives-widget.jpg
archive_type: 'monthly'
show_count: true

## Friends
friends: [
    {
        title: "GitHub-Demo",
        href: "https://github.com/GTRgoSky/TestLOL"
    }
]


# 使用的一些网站 && 教程 
## "https://eirunye.github.io/2018/09/02/Hexo搭建GitHub博客—打造炫酷的Next主题—高级—三/#more"